<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:param name="strToolbarType"/>
	<xsl:param name="parCurrRoleId"/>
	<xsl:param name="parCurrPhaseId"/>
	<xsl:param name="parFirstPhaseId"/>
	<xsl:param name="parGroupId"/>
	<xsl:param name="QueryStringInfo"/>
	<xsl:param name="RolesInfo"/>
	<xsl:param name="strPathToRoot"/>
	<xsl:param name="blnOtherRoleExist"/>
	<!-- This is an xml string generated by a DataSet. See PFM-1119 and GetToolsRow method of EHBSideMenuControl. -->
	<xsl:param name="externalDimensionValues"/>

	<xsl:template match="/">
		<xsl:if test="($blnOtherRoleExist=true() or $strToolbarType!='')">
			<!--<xsl:attribute name="action"><xsl:value-of select="concat($strPathToRoot,'toolbarController.asp')"/></xsl:attribute>-->
			<select id="selToolbar" name='selToolbar'>
				<option selected="true">--Tools Menu--</option>
				<xsl:if test="$strToolbarType='tb_phase_role'">
					<xsl:apply-templates select="headerConfig/phases/phase[@id=$parCurrPhaseId]/role[@id=$parCurrRoleId]/toolbar"/>
				</xsl:if>
				<xsl:if test="$strToolbarType='tb_application'">
					<xsl:apply-templates select="headerConfig/ehb/application/toolbar"/>
				</xsl:if>
				<xsl:if test="$strToolbarType='tb_role'">
					<xsl:apply-templates select="headerConfig/ehb/roles/role[@id=$parCurrRoleId]/toolbar"/>
				</xsl:if>
				<xsl:if test="$strToolbarType='tb_grantFolder'">
					<xsl:apply-templates select="headerConfig/ehb/grantFolder/toolbar"/>
				</xsl:if>
				<xsl:if test="$strToolbarType='tb_applicationFolder'">
					<xsl:apply-templates select="headerConfig/ehb/applicationFolder/toolbar"/>
				</xsl:if>
				<!--<xsl:if test="$blnOtherRoleExist">
					<option>Available Roles</option>
					<xsl:for-each select="$RolesInfo/role">
						--><!-- Value of the URL , the reason the STRPATHTOROOT has not been appended over here
						 is that the TOOLBAR.asp appends the path to the root --><!--
						<option>
							<xsl:attribute name="value">
								<xsl:value-of select="@url"/>
							</xsl:attribute>
							<xsl:value-of select="label"/>
						</option>
					</xsl:for-each>
				</xsl:if>-->
			</select>
		</xsl:if>
	</xsl:template>

	<xsl:template match="toolbar">
		<xsl:for-each select="group">
			<xsl:call-template name="write_toolbar">
				<xsl:with-param name="group_id">
					<xsl:value-of select="@id"/>
				</xsl:with-param>
			</xsl:call-template>
		</xsl:for-each>
	</xsl:template>

	<xsl:template name="write_toolbar">
		<xsl:param name="group_id"/>
		<xsl:for-each select="//headerConfig/toolbar/group[@id=$group_id]">
			<option>
				--<xsl:value-of select="label"/>--
			</option>
			<xsl:for-each select="item" >
				<xsl:variable name="currItemID" select="./@id"/>
				<xsl:choose>
					<xsl:when test="($strToolbarType='tb_phase_role' and @id[.= //phase[@id=$parCurrPhaseId]/role[@id=$parCurrRoleId]/toolbar/group[@id=$group_id]/item[@display='hide']/@id]) 
					or ($strToolbarType='tb_applicationFolder' and @id[.= //ehb/applicationFolder/toolbar/group[@id=$group_id]/item[@display='hide']/@id]) 
					or ($strToolbarType='tb_application' and @id[.= //ehb/application/toolbar/group[@id=$group_id]/item[@display='hide']/@id])
					or ($strToolbarType='tb_grantFolder' and @id[.= //ehb/grantFolder/toolbar/group[@id=$group_id]/item[@display='hide']/@id])
					or ($strToolbarType='tb_role' and @id[.= //ehb/roles/role[@id=$parCurrRoleId]/toolbar/group[@id=$group_id]/item[@display='hide']/@id])
					"/>
					<xsl:otherwise>
						<option>
							<xsl:attribute name="value">
								<!-- PFM-1119. The following 3 attributes/variables will only be set under rare circumstances, but if they are there, we'll cache a copy of them for out xpath query -->
								<xsl:variable name="alternateWebsiteUrl" select="@externalSystemCode and @externalSystemDimensionCode" />
								<xsl:variable name="externalSystemCode" select="@externalSystemCode" />
								<xsl:variable name="externalSystemDimensionCode" select="@externalSystemDimensionCode" />
								<xsl:choose>
									<!-- If a querystring exists that has to be appended -->
									<xsl:when test="$QueryStringInfo/type[@id='TOOLBAR']/url[@id = $currItemID]">
										<xsl:choose>

											<xsl:when test="contains(url, '?')">
												<xsl:choose>
													<xsl:when test="$alternateWebsiteUrl">
														<xsl:variable name="dimensionValue" select="$externalDimensionValues//Table[@ExternalSystemCode=$externalSystemCode][@ExternalSystemDimensionCode=$externalSystemDimensionCode]/text()" />
														<xsl:value-of select="concat(substring-before(url, '|'), '|', $dimensionValue, '|', substring-after(url, '|'),'&amp;', $QueryStringInfo/type[@id='TOOLBAR']/url[@id = $currItemID] )" />
													</xsl:when>
													<xsl:otherwise>
														<xsl:value-of select="concat(substring-before(url, '|'), '|', $strPathToRoot, '|', substring-after(url, '|'),'&amp;', $QueryStringInfo/type[@id='TOOLBAR']/url[@id = $currItemID] )" />
													</xsl:otherwise>
												</xsl:choose>
											</xsl:when>

											<xsl:otherwise>
												<xsl:choose>
													<xsl:when test="$alternateWebsiteUrl">
														<xsl:variable name="dimensionValue" select="$externalDimensionValues//Table[@ExternalSystemCode=$externalSystemCode][@ExternalSystemDimensionCode=$externalSystemDimensionCode]/text()" />
														<xsl:value-of select="concat( substring-before(url, '|'), '|', $dimensionValue, '|', substring-after(url, '|'),'?', $QueryStringInfo/type[@id='TOOLBAR']/url[@id = $currItemID] )" />
													</xsl:when>
													<xsl:otherwise>
														<xsl:value-of select="concat( substring-before(url, '|'), '|', $strPathToRoot, '|', substring-after(url, '|'),'?', $QueryStringInfo/type[@id='TOOLBAR']/url[@id = $currItemID] )" />
													</xsl:otherwise>
												</xsl:choose>
											</xsl:otherwise>

										</xsl:choose>
									</xsl:when>

									<!-- If no query String has to be appended -->
									<xsl:otherwise>
										<xsl:choose>
											<xsl:when test="$alternateWebsiteUrl">
												<xsl:variable name="dimensionValue" select="$externalDimensionValues//Table[@ExternalSystemCode=$externalSystemCode][@ExternalSystemDimensionCode=$externalSystemDimensionCode]/text()" />
												<xsl:value-of select="concat(substring-before(url, '|'), '|', $dimensionValue, '|', substring-after(url, '|'))"/>
											</xsl:when>
											<xsl:otherwise>
												<xsl:value-of select="concat(substring-before(url, '|'), '|', $strPathToRoot, '|', substring-after(url, '|'))"/>
											</xsl:otherwise>
										</xsl:choose>
									</xsl:otherwise>

								</xsl:choose>

							</xsl:attribute>
							<xsl:value-of select="label"/>
						</option>
					</xsl:otherwise>
				</xsl:choose>
			</xsl:for-each>
		</xsl:for-each>
	</xsl:template>
</xsl:stylesheet>
